/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package telas;

import classes.Departamento;
import dao.DepartamentoDAO;
import java.awt.HeadlessException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Bruno
 */
public class DepartamentoJFrame extends javax.swing.JFrame {
    
     private TabelaDepartamentos tabelaDep;
     private int linhaClicada = -1;

    /**
     * Creates new form DepartamentoJFrame
     */
    public DepartamentoJFrame() {
        tabelaDep = new TabelaDepartamentos();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnInserirDep = new javax.swing.JButton();
        btnAttDep = new javax.swing.JButton();
        campoDep = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        btnListarDep = new javax.swing.JButton();
        btnLimparTabela = new javax.swing.JButton();
        btnExcluirDep = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Departamento (nome): ");

        btnInserirDep.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnInserirDep.setText("Inserir");
        btnInserirDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirDepActionPerformed(evt);
            }
        });

        btnAttDep.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAttDep.setText("Atualizar");
        btnAttDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttDepActionPerformed(evt);
            }
        });

        tabela.setModel(tabelaDep);
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        btnListarDep.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnListarDep.setText("Listar");
        btnListarDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarDepActionPerformed(evt);
            }
        });

        btnLimparTabela.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLimparTabela.setText("Limpar");
        btnLimparTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparTabelaActionPerformed(evt);
            }
        });

        btnExcluirDep.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnExcluirDep.setText("Excluir");
        btnExcluirDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirDepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnInserirDep)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAttDep)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(campoDep, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnListarDep)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimparTabela)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluirDep)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListarDep)
                    .addComponent(btnLimparTabela)
                    .addComponent(btnExcluirDep))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInserirDep)
                    .addComponent(btnAttDep))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInserirDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirDepActionPerformed
        Departamento dep = new Departamento();
        dep.setDepartamento(campoDep.getText());
        campoDep.setText(null);
        DepartamentoDAO dao = null;
        try {
            dao = new DepartamentoDAO();
            dao.insertDepartamento(dep);
            JOptionPane.showMessageDialog(null,"Departamento inserido com sucesso!");
        } catch (HeadlessException ex) {
            JOptionPane.showMessageDialog(null,"Erro ao atualizar no banco de dados. E="+ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
        tabelaDep.insetDepartamento(dep);
    }//GEN-LAST:event_btnInserirDepActionPerformed

    private void btnAttDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttDepActionPerformed
        if(linhaClicada != -1){
            Departamento departamento = tabelaDep.getDepartamento(linhaClicada);
            
            departamento.setDepartamento(campoDep.getText());
            
            DepartamentoDAO dao = null;
            try {
                dao = new DepartamentoDAO();
                dao.updateDepartamento(departamento);
                JOptionPane.showMessageDialog(null,"Departamento atualizado com sucesso!");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null,"Erro ao atualizar no banco de dados. E="+ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            }
            //Atualiza tabela
            tabelaDep.fireTableRowsUpdated(linhaClicada, linhaClicada);
            
        }
    }//GEN-LAST:event_btnAttDepActionPerformed
    
    private void btnListarDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarDepActionPerformed
        try {
            DepartamentoDAO dao = new DepartamentoDAO();
            tabelaDep.setListDepartamento(dao.getListDepartamento());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,"Erro ao conectar com o banco de dados.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnListarDepActionPerformed

    private void btnLimparTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparTabelaActionPerformed
        tabelaDep.clearTabela();
    }//GEN-LAST:event_btnLimparTabelaActionPerformed

    private void btnExcluirDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirDepActionPerformed
        try {
            DepartamentoDAO dao = new DepartamentoDAO();
            int[] linhasSelecionadas = tabela.getSelectedRows();
            List<Departamento> listaExcluir = new ArrayList();
            for (int i = 0; i < linhasSelecionadas.length; i++) {
                Departamento departamento = tabelaDep.getDepartamento(linhasSelecionadas[i]);
                dao.deleteDepartamento(departamento);
                listaExcluir.add(departamento);

            }
            for(Departamento departamento:listaExcluir){
                tabelaDep.deleteDepartamento(departamento);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,"Erro ao realizar exclusão de contatos.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnExcluirDepActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        //Pega a linha clicada
        linhaClicada = tabela.rowAtPoint(evt.getPoint());
        //Pega o contato da linha clidada
        Departamento departamento = tabelaDep.getDepartamento(linhaClicada);
        //Seta os dados nos componentes
        campoDep.setText(departamento.getDepartamento());
    }//GEN-LAST:event_tabelaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DepartamentoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DepartamentoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DepartamentoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DepartamentoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DepartamentoJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAttDep;
    private javax.swing.JButton btnExcluirDep;
    private javax.swing.JButton btnInserirDep;
    private javax.swing.JButton btnLimparTabela;
    private javax.swing.JButton btnListarDep;
    private javax.swing.JTextField campoDep;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
