/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package telas;

import classes.Sistema;
import dao.SistemaDAO;
import java.awt.HeadlessException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Bruno
 */
public class SistemaJFrame extends javax.swing.JFrame {
    
    private TabelaSistemas tabelaSist;
    private int linhaClicada = -1;

    /**
     * Creates new form SistemaJFrame
     */
    public SistemaJFrame() {
        tabelaSist = new TabelaSistemas();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        btnExcluirSist = new javax.swing.JButton();
        btnLimparTabela = new javax.swing.JButton();
        btnListarSist = new javax.swing.JButton();
        btnAttSist = new javax.swing.JButton();
        campoSist = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnInserirSist = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabela.setModel(tabelaSist);
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        btnExcluirSist.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnExcluirSist.setText("Excluir");
        btnExcluirSist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirSistActionPerformed(evt);
            }
        });

        btnLimparTabela.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLimparTabela.setText("Limpar");
        btnLimparTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparTabelaActionPerformed(evt);
            }
        });

        btnListarSist.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnListarSist.setText("Listar");
        btnListarSist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarSistActionPerformed(evt);
            }
        });

        btnAttSist.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAttSist.setText("Atualizar");
        btnAttSist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttSistActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Sistema (nome): ");

        btnInserirSist.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnInserirSist.setText("Inserir");
        btnInserirSist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirSistActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnInserirSist)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAttSist))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(campoSist, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnListarSist)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnLimparTabela)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnExcluirSist))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListarSist)
                    .addComponent(btnLimparTabela)
                    .addComponent(btnExcluirSist))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoSist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInserirSist)
                    .addComponent(btnAttSist))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        //Pega a linha clicada
        linhaClicada = tabela.rowAtPoint(evt.getPoint());
        //Pega o contato da linha clidada
        Sistema sistema = tabelaSist.getSistema(linhaClicada);
        //Seta os dados nos componentes
        campoSist.setText(sistema.getSistema());
    }//GEN-LAST:event_tabelaMouseClicked

    private void btnExcluirSistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirSistActionPerformed
        try {
            SistemaDAO dao = new SistemaDAO();
            int[] linhasSelecionadas = tabela.getSelectedRows();
            List<Sistema> listaExcluir = new ArrayList();
            for (int i = 0; i < linhasSelecionadas.length; i++) {
                Sistema sistema = tabelaSist.getSistema(linhasSelecionadas[i]);
                dao.deleteSistema(sistema);
                listaExcluir.add(sistema);

            }
            for(Sistema sistema:listaExcluir){
                tabelaSist.deleteSistema(sistema);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,"Erro ao realizar exclusão de sistemas.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnExcluirSistActionPerformed

    private void btnLimparTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparTabelaActionPerformed
        tabelaSist.clearTabela();
    }//GEN-LAST:event_btnLimparTabelaActionPerformed

    private void btnListarSistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarSistActionPerformed
        try {
            SistemaDAO dao = new SistemaDAO();
            tabelaSist.setListSistema(dao.getListSistema());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,"Erro ao conectar com o banco de dados.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnListarSistActionPerformed

    private void btnAttSistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttSistActionPerformed
        if(linhaClicada != -1){
            Sistema sistema = tabelaSist.getSistema(linhaClicada);

            sistema.setSistema(campoSist.getText());

            SistemaDAO dao = null;
            try {
                dao = new SistemaDAO();
                dao.updateSistema(sistema);
                JOptionPane.showMessageDialog(null,"Sistema atualizado com sucesso!");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null,"Erro ao atualizar no banco de dados. E="+ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            }
            //Atualiza tabela
            tabelaSist.fireTableRowsUpdated(linhaClicada, linhaClicada);

        }
    }//GEN-LAST:event_btnAttSistActionPerformed

    private void btnInserirSistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirSistActionPerformed
        Sistema sistema = new Sistema();
        sistema.setSistema(campoSist.getText());
        campoSist.setText(null);
        SistemaDAO dao = null;
        try {
            dao = new SistemaDAO();
            dao.insertSistema(sistema);
            JOptionPane.showMessageDialog(null,"Sistema inserido com sucesso!");
        } catch (HeadlessException ex) {
            JOptionPane.showMessageDialog(null,"Erro ao atualizar no banco de dados. E="+ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
        tabelaSist.insetSistema(sistema);
    }//GEN-LAST:event_btnInserirSistActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SistemaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SistemaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SistemaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SistemaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SistemaJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAttSist;
    private javax.swing.JButton btnExcluirSist;
    private javax.swing.JButton btnInserirSist;
    private javax.swing.JButton btnLimparTabela;
    private javax.swing.JButton btnListarSist;
    private javax.swing.JTextField campoSist;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
